'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class [Event]
    Public Property IdEvent As Integer
    Public Property EventName As String
    Public Property IdUser As Integer
    Public Property EventDate As Date
    Public Property EventPlace As String
    Public Property Description As String

    Public Overridable Property User As User
    Public Overridable Property EventRelation As ICollection(Of EventRelation) = New HashSet(Of EventRelation)
    Public Overridable Property Gift_Relation_Event As ICollection(Of Gift_Relation_Event) = New HashSet(Of Gift_Relation_Event)
    Public Overridable Property Forum_Event As ICollection(Of Forum_Event) = New HashSet(Of Forum_Event)

End Class
