'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EventRelation
    Public Property IdEvent As Integer
    Public Property IdRelation As Integer
    Public Property IdEventRelation As Integer

    Public Overridable Property [Event] As [Event]
    Public Overridable Property Relation As Relation
    Public Overridable Property Forum_Event As ICollection(Of Forum_Event) = New HashSet(Of Forum_Event)

End Class
