'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Forum_Event
    Public Property IdEventRelation As Integer
    Public Property IdEvent As Integer
    Public Property [Date] As Date
    Public Property Comment As String

    Public Overridable Property [Event] As [Event]
    Public Overridable Property EventRelation As EventRelation

End Class
