'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Gift_Relation_Event
    Public Property IdGift As Integer
    Public Property IdRelation As Integer
    Public Property IdEvent As Integer

    Public Overridable Property [Event] As [Event]
    Public Overridable Property Gift As Gift
    Public Overridable Property Relation As Relation

End Class
