'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Gift
    Public Property IdGift As Integer
    Public Property IdUser As Integer
    Public Property Gift1 As String
    Public Property Price As Nullable(Of Decimal)
    Public Property Size As String
    Public Property Brand As String
    Public Property Color As String
    Public Property Description As String
    Public Property Photo As Byte()

    Public Overridable Property User As User
    Public Overridable Property Gift_Relation_Event As ICollection(Of Gift_Relation_Event) = New HashSet(Of Gift_Relation_Event)

End Class
