'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class s17041Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=s17041Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property [Event]() As DbSet(Of [Event])
    Public Overridable Property EventRelation() As DbSet(Of EventRelation)
    Public Overridable Property Forum_Event() As DbSet(Of Forum_Event)
    Public Overridable Property Gift() As DbSet(Of Gift)
    Public Overridable Property Gift_Relation_Event() As DbSet(Of Gift_Relation_Event)
    Public Overridable Property Hobby() As DbSet(Of Hobby)
    Public Overridable Property Relation() As DbSet(Of Relation)
    Public Overridable Property User() As DbSet(Of User)
    Public Overridable Property User_Hobby() As DbSet(Of User_Hobby)

End Class
